owner: merlinfuchs # Your GitHub organization or username, where this repository lives
repo: embedg-uptime # The name of this repository

sites:
  - name: Embed Generator Website
    url: https://message.style/
  - name: Embed Generator App
    url: https://message.style/app
  - name: Embed Generator API
    url: https://message.style/api/users/@me
    expectedStatusCodes:
      - 401

status-website:
  cname: status.message.style
  # baseUrl: /embedg-uptime
  logoUrl: https://message.style/img/logo.svg
  favicon: https://message.style/img/logo-256.png
  faviconSvg: https://message.style/img/logo.svg
  name: Embed Generator Status
  introTitle: "**Embed Generator** is the best way to create fancy messages for your Discord Server."
  introMessage: This page shows the status and uptime of Embed Generator and the related services. If you are looking for the Embed Generator website click [here](https://message.style)!
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://message.style


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
